// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK6_1sXpa-BnTtAZw2uKmVsYuQQoupL7Y',
    appId: '1:211948202240:web:cce838d44ee7831942ebe5',
    messagingSenderId: '211948202240',
    projectId: 'fitcentive-1210',
    authDomain: 'fitcentive-1210.firebaseapp.com',
    databaseURL: 'https://fitcentive-1210.firebaseio.com',
    storageBucket: 'fitcentive-1210.appspot.com',
    measurementId: 'G-MZ4R425SMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT0w9ShI2Q-7G7ixF-JfBXGj8AcKnMDeE',
    appId: '1:211948202240:android:26e9a4749f0af8a342ebe5',
    messagingSenderId: '211948202240',
    projectId: 'fitcentive-1210',
    databaseURL: 'https://fitcentive-1210.firebaseio.com',
    storageBucket: 'fitcentive-1210.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyzn-UB4LteGd8wa-wj6zBYs_k7Ks0aYk',
    appId: '1:211948202240:ios:0bf809f34f80cfa242ebe5',
    messagingSenderId: '211948202240',
    projectId: 'fitcentive-1210',
    databaseURL: 'https://fitcentive-1210.firebaseio.com',
    storageBucket: 'fitcentive-1210.appspot.com',
    androidClientId: '211948202240-7vnfnk5bmj5hq5i1e897c02gcljjacd8.apps.googleusercontent.com',
    iosClientId: '211948202240-3b0pv8dm57t4dpntdoqvge043smn0is6.apps.googleusercontent.com',
    iosBundleId: 'io.fitcentive.flutterApp',
  );

  static const String vapidKey = "BJ_7Fj08xF9KFTkV5SS7kFoyKUr3MH2nPjNRUVp0sHfCY8bBNlbiLOm_gOSytQDEjTNjMns3S01or9x5Fd5Fdq8";
}
