// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Note - download and place/replace .plist/.json files as required in android/ios directories
  //        find instructions in firebase console under android/ios app settings
  // Get API key from https://console.cloud.google.com/apis/credentials?authuser=1&orgonly=true&project=fitcentive-dev&supportedpurview=organizationId,folder,project
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARqvT6yJ-P2imc8-595kH5nsVDEpdt-kE',
    appId: '1:27981216008:android:9e823848112e98c5d954bd',
    messagingSenderId: '27981216008',
    projectId: 'fitcentive-dev-02',
    authDomain: 'fitcentive-dev-02.firebaseapp.com',
    databaseURL: 'https://fitcentive-dev-02.firebaseio.com',
    storageBucket: 'fitcentive-dev-02.appspot.com',
    measurementId: 'G-MZ4R425SMP', // Not used perhaps
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARqvT6yJ-P2imc8-595kH5nsVDEpdt-kE',
    appId: '1:27981216008:android:9e823848112e98c5d954bd',
    messagingSenderId: '27981216008',
    projectId: 'fitcentive-dev-02',
    databaseURL: 'https://fitcentive-dev-02.firebaseio.com',
    storageBucket: 'fitcentive-dev-02.appspot.com',
  );

  // Register APNS key in Firebase console project cloud messaging settings
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARqvT6yJ-P2imc8-595kH5nsVDEpdt-kE',
    appId: '1:27981216008:android:9e823848112e98c5d954bd',
    messagingSenderId: '27981216008',
    projectId: 'fitcentive-dev-02',
    databaseURL: 'https://fitcentive-dev-02.firebaseio.com',
    storageBucket: 'fitcentive-dev-02.appspot.com',
    androidClientId: '27981216008-lccq2unlfjg9n757rol6459gduefgu0q.apps.googleusercontent.com',
    iosClientId: '27981216008-lccq2unlfjg9n757rol6459gduefgu0q.apps.googleusercontent.com',
    iosBundleId: 'io.fitcentive.flutterApp',
  );

  // Create a web push certificate - keyPair is vapidKey
  static const String vapidKey = "BOmo03Cmmi0JC6g8n1045_Hum3BdHPMZG7wJpm0QUKqDUxd2K-HeEOnUDAB2dz8cp4OmKP27o5Y1I4M66YzICFM";
}
