// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Note - download and place/replace .plist/.json files as required in android/ios directories
  //        find instructions in firebase console under android/ios app settings
  // Get API key from https://console.cloud.google.com/apis/credentials?authuser=1&orgonly=true&project=fitcentive-dev&supportedpurview=organizationId,folder,project
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLWpPaBj5uvuRaOev3SDB3zLW32WfupYU',
    appId: '1:675708031489:web:6757ea293a9cd20298a600',
    messagingSenderId: '675708031489',
    projectId: 'fitcentive-dev-03',
    authDomain: 'fitcentive-dev-03.firebaseapp.com',
    databaseURL: 'https://fitcentive-dev-03.firebaseio.com',
    storageBucket: 'fitcentive-dev-03.appspot.com',
    measurementId: 'G-MZ4R425SMP', // Not used perhaps
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIkAL_wZd8u8HM6qr7YXmGH9fiWM5YdRQ',
    appId: '1:675708031489:android:013a6952d66033b098a600',
    messagingSenderId: '675708031489',
    projectId: 'fitcentive-dev-03',
    databaseURL: 'https://fitcentive-dev-03.firebaseio.com',
    storageBucket: 'fitcentive-dev-03.appspot.com',
  );

  // Register APNS key in Firebase console project cloud messaging settings
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrKoIZ66J2EMe520apZDMdXgfj7b2Fv9g',
    appId: '1:675708031489:ios:0ff3ff88f486cb7f98a600',
    messagingSenderId: '675708031489',
    projectId: 'fitcentive-dev-03',
    databaseURL: 'https://fitcentive-dev-03.firebaseio.com',
    storageBucket: 'fitcentive-dev-03.appspot.com',
    androidClientId: '675708031489-gknap6b7r9illrfnu79ll9ti8l9mqft4.apps.googleusercontent.com',
    iosClientId: '675708031489-gknap6b7r9illrfnu79ll9ti8l9mqft4.apps.googleusercontent.com',
    iosBundleId: 'io.fitcentive.flutterApp',
  );

  // Create a web push certificate - keyPair is vapidKey
   static const String vapidKey = "BATkvrqrmE6xSMWeLWRkAccjhI6y1JpvtsIGxVcUaFtEPqWMoJJBhPTePfM3I-tnzEQxrObTptp6u98SeEeEkEA";
}
